/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RedirectToSocks5Service */

#ifndef _Included_RedirectToSocks5Service
#define _Included_RedirectToSocks5Service
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RedirectToSocks5Service
 * Method:    start
 * Signature: (Ljava/lang/String;ILjava/lang/String;ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_RedirectToSocks5Service_start
  (JNIEnv *, jclass, jstring, jint, jstring, jint, jstring, jstring);

/*
 * Class:     RedirectToSocks5Service
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RedirectToSocks5Service_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
