/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ymbl_smartgateway_extension_IpTables */

#ifndef _Included_com_ymbl_smartgateway_extension_IpTables
#define _Included_com_ymbl_smartgateway_extension_IpTables
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ymbl_smartgateway_extension_IpTables
 * Method:    getMacAddr
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ymbl_smartgateway_extension_IpTables_getMacAddr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ymbl_smartgateway_extension_IpTables
 * Method:    rule
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ymbl_smartgateway_extension_IpTables_rule
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
