/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ymbl_smartgateway_extension_Lua */

#ifndef _Included_com_ymbl_smartgateway_extension_Lua
#define _Included_com_ymbl_smartgateway_extension_Lua
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ymbl_smartgateway_extension_Lua
 * Method:    getMacAddr
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ymbl_smartgateway_extension_Lua_getMacAddr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ymbl_smartgateway_extension_Lua
 * Method:    exec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ymbl_smartgateway_extension_Lua_exec
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
