/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ymbl_smartgateway_extension_XL2tpd */

#ifndef _Included_com_ymbl_smartgateway_extension_XL2tpd
#define _Included_com_ymbl_smartgateway_extension_XL2tpd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ymbl_smartgateway_extension_XL2tpd
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ymbl_smartgateway_extension_XL2tpd_start
  (JNIEnv *, jobject);

/*
 * Class:     com_ymbl_smartgateway_extension_XL2tpd
 * Method:    route
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ymbl_smartgateway_extension_XL2tpd_route
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
