/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ymbl_smartgateway_extension_RedirectToSocks5Service */

#ifndef _Included_com_ymbl_smartgateway_extension_RedirectToSocks5Service
#define _Included_com_ymbl_smartgateway_extension_RedirectToSocks5Service
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ymbl_smartgateway_extension_RedirectToSocks5Service
 * Method:    start
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ymbl_smartgateway_extension_RedirectToSocks5Service_start
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_ymbl_smartgateway_extension_RedirectToSocks5Service
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ymbl_smartgateway_extension_RedirectToSocks5Service_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
