/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ymbl_smartgateway_transite_TransiteActivator */

#ifndef _Included_com_ymbl_smartgateway_transite_TransiteActivator
#define _Included_com_ymbl_smartgateway_transite_TransiteActivator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ymbl_smartgateway_transite_TransiteActivator
 * Method:    getMacAddr
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jstring JNICALL Java_com_ymbl_smartgateway_transite_TransiteActivator_getMacAddr
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
